In [6]:
import numpy as np
import pandas as pd



In [7]:
x = np.array([0, 1, 2, 3])
x

w = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])
w

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [8]:
x = np.array([0, 1, 2, 3])

# Square each value.
print(np.square(x))

# Square root of each value.
print(np.sqrt(x))

# Cosine of each value.
print(np.cos(x))


[0 1 4 9]
[ 0.          1.          1.41421356  1.73205081]
[ 1.          0.54030231 -0.41614684 -0.9899925 ]


In [9]:
x = np.array([0, 1, 2, 3])

# Find the maximum value.
print(np.max(x))

# Find the minimum value.
print(np.min(x))

# Find the mean of the input array.
print(np.mean(x))

# Find the standard deviation of the input array.
print(np.std(x))

3
0
1.5
1.11803398875


In [10]:
my_array = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
df = pd.DataFrame(my_array)
df

0  1  2  3
0  0  1  2  3
1  4  5  6  7

In [11]:
df.columns = ['first', 'this', 'that', 'last']
df.index = ['row_1', 'row_2']
df

first  this  that  last
row_1      0     1     2     3
row_2      4     5     6     7

In [12]:
df2 = pd.DataFrame(
    my_array,
    columns=['first', 'this', 'that', 'last'],
    index=['row_1', 'row_2'])
df2

first  this  that  last
row_1      0     1     2     3
row_2      4     5     6     7

In [13]:
# This list will become our row names.
names = ['George',
         'John',
         'Thomas',
         'James',
         'Andrew',
         'Martin',
         'William',
         'Zachary',
         'Millard',
         'Franklin']

# Create an empty data frame with named rows.
purchases = pd.DataFrame(index=names)

# Add our columns to the data frame one at a time.
purchases['country'] = ['US', 'CAN', 'CAN', 'US', 'CAN', 'US', 'US', 'US', 'CAN', 'US']
purchases['ad_views'] = [16, 42, 32, 13, 63, 19, 65, 23, 16, 77]
purchases['items_purchased'] = [2, 1, 0, 8, 0, 5, 7, 3, 0, 5]
purchases 

country  ad_views  items_purchased
George        US        16                2
John         CAN        42                1
Thomas       CAN        32                0
James         US        13                8
Andrew       CAN        63                0
Martin        US        19                5
William       US        65                7
Zachary       US        23                3
Millard      CAN        16                0
Franklin      US        77                5

In [14]:
purchases['items_purch_per_ad'] = purchases['items_purchased'] / purchases['ad_views']
purchases

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
John         CAN        42                1            0.023810
Thomas       CAN        32                0            0.000000
James         US        13                8            0.615385
Andrew       CAN        63                0            0.000000
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Millard      CAN        16                0            0.000000
Franklin      US        77                5            0.064935

In [15]:
purchases['country']

George       US
John        CAN
Thomas      CAN
James        US
Andrew      CAN
Martin       US
William      US
Zachary      US
Millard     CAN
Franklin     US
Name: country, dtype: object

In [16]:
purchases.loc['George']

country                  US
ad_views                 16
items_purchased           2
items_purch_per_ad    0.125
Name: George, dtype: object

In [17]:
purchases.loc[:, 'country']

George       US
John        CAN
Thomas      CAN
James        US
Andrew      CAN
Martin       US
William      US
Zachary      US
Millard     CAN
Franklin     US
Name: country, dtype: object

In [18]:
# loc method
purchases.loc[lambda df: purchases['items_purchased'] > 1, :]

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
James         US        13                8            0.615385
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Franklin      US        77                5            0.064935

In [20]:
# bracket method
purchases[purchases['items_purchased'] > 1]

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
James         US        13                8            0.615385
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Franklin      US        77                5            0.064935

In [21]:
purchases.groupby('country').aggregate(np.mean)

ad_views  items_purchased  items_purch_per_ad
country                                               
CAN         38.25             0.25            0.005952
US          35.50             5.00            0.217767